# Generated by Django 4.1.1 on 2023-09-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_members_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(default='user-avatar.jpeg', upload_to=''),
        ),
    ]
