# Generated by Django 4.1.1 on 2023-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_book_options_rename_bookid_book_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='text_reviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
