# Generated by Django 4.1.1 on 2023-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_book_num_pages_alter_book_text_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
