# Generated by Django 4.1.1 on 2023-09-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_book_isbn13_alter_book_ratings_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
