# Generated by Django 4.1.1 on 2023-09-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_members_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_date',
            field=models.DateField(null=True),
        ),
    ]
